### ISSUE TITLE
[Task V0] Termo de uso

### ISSUE THREAD

**Issue by ericobropinto** [CoronaTrack/CoronaTrack-pwa#18]
Em baixo do botão "Cadastre-se"incluir o texto com link "Ao se cadastrar você aceito os Termos e Condição de uso" esse link deverá abrir os termos da V0 (https://coronatrack.com.br/politica-de-privacidade-v0/)

Segue abaixo imagens de como foi implementado na V1, seguir mesmo modelo..

![image](https://user-images.githubusercontent.com/12814438/79768180-c9606d80-8300-11ea-9756-41f720b1f79d.png)

![image](https://user-images.githubusercontent.com/12814438/79768343-09275500-8301-11ea-9a3a-4cc440f94f74.png)

**Comment by brenda2s** [comment]
Duvidas: Qual é o link dos termos de uso?
Se não tiver o link e tivermos que criar o link, qual é o texto do termo de uso? quem criaria isso?

**Comment by brenda2s** [comment]
Task Impedida, pois está pendente o texto do termo.
Érico está alinhando com Rafael e Jurídico essa informação

**Comment by imortalout** [comment]
Galera eu resolvi a parte de fazer uma rota que abra a tela para o Iframe. Mas o que acontece eh que o site precisa desabilitar no header X-Frame-Options "SAMEORIGIN" para "ALLOWALL".
