### ISSUE TITLE
[Task V0] Inserir na tela de visualização do risco o vídeo correspondente.

### ISSUE THREAD

**Issue by ericobropinto** [CoronaTrack/CoronaTrack-pwa#20]
https://www.figma.com/proto/W8M3dMMNN5dyruwdC6qMze/CoronaTrack?node-id=11%3A622&viewport=365%2C394%2C0.5&scaling=scale-down

Tela 8. Ao visualizar o grau de risco, deve-se exibir também um vídeo.
Os vídeos estão em:

https://drive.google.com/drive/u/0/folders/10spzo5XVeiMMCGoswNhHgo0An4GtQP14

**Comment by brenda2s** [comment]
Dúvida,
Qual vídeo deverá ser exibido para cada perfil?

**Comment by brenda2s** [comment]
Task Impedida, pois está pendente o 3 vídeo, e a definição de qual vídeo será para cada status.
Érico está alinhando com Rafael

**Comment by brenda2s** [comment]
[16:25, 09/04/2020] Rafael Corona Track : Leve = baixo
[16:25, 09/04/2020] Rafael Corona Track : moderado = medio
[16:25, 09/04/2020] Rafael Corona Track : full = alto

Task removida do impedimento. (Videos e Status atualizado)

**Comment by brenda2s** [comment]
(Diagnóstico Moderado do Dr. André Soares) -> https://www.youtube.com/watch?v=ojBAUfy_GAA&feature=youtu.be
(Diagnóstico Leve do Dr. André Soares) -> https://www.youtube.com/watch?v=k38N-RgN4-U&feature=youtu.be

**Comment by brenda2s** [comment]
Leve -> https://www.youtube.com/watch?v=k38N-RgN4-U&feature=youtu.be
Moderado -> https://www.youtube.com/watch?v=ojBAUfy_GAA&feature=youtu.be
Grave-> https://www.youtube.com/watch?v=azyyE-P57Jg&feature=youtu.be
